language: node_js

branches:
  except:
    - /^v[0-9]/

node_js:
  - 7
  - 8

services:
  - postgresql

addons:
  postgresql: 9.6
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6
     - postgresql-9.6-postgis-2.3

before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn

before_script:
  - psql -U postgres -c 'create database test;'
  - psql -U postgres -d test -c 'create extension postgis'
  - psql -U postgres -d test -f test/table1.sql
  - greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn test

after_script:
  - greenkeeper-lockfile-upload